export const ELIG_RAW_FIELDS = [
  'CHNL_SRC_CD','LGCY_MBR_NUM','CUST_LAST_NM','CUST_FRST_NM','CUST_BRTH_DT','CUST_GENDR_CD',
  'CIGNA_RELSHP_CD','CLIENT_ACCT_NUM','ELGBTY_BRNCH_NUM','BEN_OPT_CD','CUST_ELGBTY_CVRG_EFF_DT',
  'CUST_ELGBTY_CVRG_TERM_DT','COVERAGE_TYPE','CUST_POSTL_CD','DERV_PCP_PROV_ID','CVRG_PER_YR_MTH_NUM',
  'AMI','INDIV_ENTPR_ID','DERV_SRC_SYS_CD','ACCT_TY_CD','CLIENT_ID','CUST_AGE_NUM','AGE_BAND_CD',
  'NT_ID','RT_REGN_CD','CVRG_PHRM_IND','MEDCR_AS_PRIM_IND','CUST_ADDR_LN_1','CUST_ADDR_LN_2',
  'CUST_CITY_NM','CUST_ST_CD','CVRG_MED_IND','CVRG_DENT_IND','CVRG_BEHVRAL_IND','CVRG_VSN_IND',
  'SUBSCRBR_STAT_CD','SUBGRP_ID','BEN_PLAN_NUM','SOURCEFILENAME','FILE_RECEIVED_DATE','IMPORT_DATE'
];

export const ELIG_MEMBER_STAGE_DDL = [
  'CH_MEMBER_ID VARCHAR(16777216)','CH_EMPLOYER_ID VARCHAR(16777216)','MEMBER_ID VARCHAR(16777216)',
  'GROUP_ID VARCHAR(16777216)','EMPLOYEE_ID VARCHAR(16777216)','FIRST_NAME VARCHAR(16777216)',
  'MIDDLE_NAME VARCHAR(16777216)','LAST_NAME VARCHAR(16777216)','SSN VARCHAR(16777216)','GENDER VARCHAR(16777216)',
  'DOB DATE','ADDRESS_1 VARCHAR(16777216)','ADDRESS_2 VARCHAR(16777216)','CITY VARCHAR(16777216)',
  'COUNTY VARCHAR(16777216)','STATE VARCHAR(16777216)','ZIP_CODE VARCHAR(16777216)','MARITAL_STATUS VARCHAR(16777216)',
  'RACE VARCHAR(16777216)','ETHNIC_GROUP VARCHAR(16777216)','EDUCATION_LEVEL VARCHAR(16777216)','RELATIONSHIP VARCHAR(16777216)',
  'AGE_RANGE VARCHAR(16777216)','OFFICE_LOCATION VARCHAR(16777216)','ALTERNATE_MEMBER_ID VARCHAR(16777216)',
  'PHONE_HOME VARCHAR(16777216)','PHONE_WORK VARCHAR(16777216)','PHONE_MOBILE VARCHAR(16777216)',
  'EMAIL_ADDRESS_HOME VARCHAR(16777216)','EMAIL_ADDRESS_WORK VARCHAR(16777216)','MEMBER_STATUS VARCHAR(16777216)',
  'PHS_REVIEWED VARCHAR(16777216)','ENGAGED VARCHAR(16777216)','MERGE_DT DATE','MERGED_INTO VARCHAR(16777216)',
  'PHA_ENGAGEMENT_DATE DATE','CC_ENGAGEMENT_DATE DATE','PROGRAM_TYPE_ID VARCHAR(16777216)',
  'FIRST_NAME_EDITED VARCHAR(16777216)','MIDDLE_NAME_EDITED VARCHAR(16777216)','LAST_NAME_EDITED VARCHAR(16777216)',
  'GENDER_EDITED VARCHAR(16777216)','ADDRESS_1_EDITED VARCHAR(16777216)','ADDRESS_2_EDITED VARCHAR(16777216)',
  'CITY_EDITED VARCHAR(16777216)','STATE_EDITED VARCHAR(16777216)','ZIP_CODE_EDITED VARCHAR(16777216)',
  'EMAIL_ADDRESS_EDITED VARCHAR(16777216)','CELL_PHONE_EDITED VARCHAR(16777216)','WORK_PHONE_EDITED VARCHAR(16777216)',
  'HOME_PHONE_EDITED VARCHAR(16777216)','ETHNIC_GROUP_EDITED VARCHAR(16777216)','USER_LAST_EDITED_BY_ID VARCHAR(16777216)',
  'LAST_EDITED_TIMESTAMP TIMESTAMP_NTZ','UDF1 VARCHAR(16777216)','UDF2 VARCHAR(16777216)',
  'EFFECTIVE_DATE DATE','TERMINATION_DATE DATE',
  'SOURCEFILENAME VARCHAR(16777216)','RECEIVED_DATE DATE','IMPORT_DATE DATE','SCRUBBED_DATE DATE',
  'DATA_SOURCE VARCHAR(16777216)','JOB_TITLE VARCHAR(16777216)','INCOME_LEVEL VARCHAR(16777216)',
  'BUSINESS_UNIT VARCHAR(16777216)','EMPLOYEE_SSN VARCHAR(16777216)','EMPLOYEE_FIRST_NAME VARCHAR(16777216)',
  'EMPLOYEE_MIDDLE_NAME VARCHAR(16777216)','EMPLOYEE_LAST_NAME VARCHAR(16777216)','PCP_NPI VARCHAR(16777216)',
  'PCP_NAME VARCHAR(16777216)','PCP_DATE_LAST_SEEN DATE','PCP_DATE_FIRST_SEEN DATE','ENGAGED_WITH_PCP VARCHAR(16777216)',
  'NO_OF_PCP_VISITS_SEEN_LAST12_MONTHS VARCHAR(16777216)','PCP_SOURCE VARCHAR(16777216)',
  'ATTRIBUTED_PCP_NPI VARCHAR(16777216)','ATTRIBUTED_PCP_NAME VARCHAR(16777216)',
  'ATTRIBUTED_PCP_DATE_LAST_SEEN DATE','ATTRIBUTED_PCP_DATE_FIRST_SEEN DATE','ENGAGED_WITH_ATTRIBUTED_PCP VARCHAR(16777216)',
  'NO_OF_ATTRIBUTED_PCP_VISITS_SEEN_LAST12_MONTHS VARCHAR(16777216)','ATTRIBUTED_PCP_SOURCE VARCHAR(16777216)',
  'UDF3 VARCHAR(16777216)','UDF4 VARCHAR(16777216)','UDF5 VARCHAR(16777216)'
];

export const ELIG_DEFAULTS = [
  {target:'CH_MEMBER_ID',type:'null',value:''},
  {target:'CH_EMPLOYER_ID',type:'null',value:''},
  {target:'MEMBER_ID',type:'direct',value:'LGCY_MBR_NUM'},
  {target:'GROUP_ID',type:'direct',value:'CLIENT_ACCT_NUM'},
  {target:'EMPLOYEE_ID',type:'expression',value:'LEFT(LGCY_MBR_NUM, LENGTH(LGCY_MBR_NUM) - 1)'},
  {target:'FIRST_NAME',type:'direct',value:'CUST_FRST_NM'},
  {target:'MIDDLE_NAME',type:'null',value:''},
  {target:'LAST_NAME',type:'direct',value:'CUST_LAST_NM'},
  {target:'SSN',type:'null',value:''},
  {target:'GENDER',type:'direct',value:'CUST_GENDR_CD'},
  {target:'DOB',type:'expression',value:"TO_DATE(CUST_BRTH_DT,'YYYYMMDD')"},
  {target:'ADDRESS_1',type:'direct',value:'CUST_ADDR_LN_1'},
  {target:'ADDRESS_2',type:'direct',value:'CUST_ADDR_LN_2'},
  {target:'CITY',type:'direct',value:'CUST_CITY_NM'},
  {target:'COUNTY',type:'null',value:''},
  {target:'STATE',type:'direct',value:'CUST_ST_CD'},
  {target:'ZIP_CODE',type:'direct',value:'CUST_POSTL_CD'},
  {target:'MARITAL_STATUS',type:'null',value:''},
  {target:'RACE',type:'null',value:''},
  {target:'ETHNIC_GROUP',type:'null',value:''},
  {target:'EDUCATION_LEVEL',type:'null',value:''},
  {target:'RELATIONSHIP',type:'expression',value:"CASE WHEN CIGNA_RELSHP_CD='EE' THEN 'EMPLOYEE' WHEN CIGNA_RELSHP_CD='SP' THEN 'SPOUSE' WHEN CIGNA_RELSHP_CD='CH' THEN 'DEPENDENT' ELSE CIGNA_RELSHP_CD END"},
  {target:'EFFECTIVE_DATE',type:'expression',value:"TO_DATE(NULLIF(TRIM(CUST_ELGBTY_CVRG_EFF_DT),''),'YYYYMMDD')"},
  {target:'TERMINATION_DATE',type:'expression',value:"TO_DATE(NULLIF(TRIM(CUST_ELGBTY_CVRG_TERM_DT),''),'YYYYMMDD')"},
  {target:'AGE_RANGE',type:'direct',value:'AGE_BAND_CD'},
  {target:'OFFICE_LOCATION',type:'null',value:''},
  {target:'ALTERNATE_MEMBER_ID',type:'direct',value:'AMI'},
  {target:'PHONE_HOME',type:'null',value:''},
  {target:'PHONE_WORK',type:'null',value:''},
  {target:'PHONE_MOBILE',type:'null',value:''},
  {target:'EMAIL_ADDRESS_HOME',type:'null',value:''},
  {target:'EMAIL_ADDRESS_WORK',type:'null',value:''},
  {target:'MEMBER_STATUS',type:'direct',value:'SUBSCRBR_STAT_CD'},
  {target:'PHS_REVIEWED',type:'null',value:''},
  {target:'ENGAGED',type:'null',value:''},
  {target:'MERGE_DT',type:'null',value:''},
  {target:'MERGED_INTO',type:'null',value:''},
  {target:'PHA_ENGAGEMENT_DATE',type:'null',value:''},
  {target:'CC_ENGAGEMENT_DATE',type:'null',value:''},
  {target:'PROGRAM_TYPE_ID',type:'null',value:''},
  {target:'FIRST_NAME_EDITED',type:'null',value:''},
  {target:'MIDDLE_NAME_EDITED',type:'null',value:''},
  {target:'LAST_NAME_EDITED',type:'null',value:''},
  {target:'GENDER_EDITED',type:'null',value:''},
  {target:'ADDRESS_1_EDITED',type:'null',value:''},
  {target:'ADDRESS_2_EDITED',type:'null',value:''},
  {target:'CITY_EDITED',type:'null',value:''},
  {target:'STATE_EDITED',type:'null',value:''},
  {target:'ZIP_CODE_EDITED',type:'null',value:''},
  {target:'EMAIL_ADDRESS_EDITED',type:'null',value:''},
  {target:'CELL_PHONE_EDITED',type:'null',value:''},
  {target:'WORK_PHONE_EDITED',type:'null',value:''},
  {target:'HOME_PHONE_EDITED',type:'null',value:''},
  {target:'ETHNIC_GROUP_EDITED',type:'null',value:''},
  {target:'USER_LAST_EDITED_BY_ID',type:'null',value:''},
  {target:'LAST_EDITED_TIMESTAMP',type:'null',value:''},
  {target:'UDF1',type:'direct',value:'INDIV_ENTPR_ID'},
  {target:'UDF2',type:'direct',value:'DERV_PCP_PROV_ID'},
  {target:'SOURCEFILENAME',type:'direct',value:'SOURCEFILENAME'},
  {target:'RECEIVED_DATE',type:'direct',value:'FILE_RECEIVED_DATE'},
  {target:'IMPORT_DATE',type:'direct',value:'IMPORT_DATE'},
  {target:'SCRUBBED_DATE',type:'expression',value:'CURRENT_DATE()'},
  {target:'DATA_SOURCE',type:'hardcoded',value:'ELIGIBILITY'},
  {target:'JOB_TITLE',type:'null',value:''},
  {target:'INCOME_LEVEL',type:'null',value:''},
  {target:'BUSINESS_UNIT',type:'null',value:''},
  {target:'EMPLOYEE_SSN',type:'null',value:''},
  {target:'EMPLOYEE_FIRST_NAME',type:'null',value:''},
  {target:'EMPLOYEE_MIDDLE_NAME',type:'null',value:''},
  {target:'EMPLOYEE_LAST_NAME',type:'null',value:''},
  {target:'PCP_NPI',type:'null',value:''},
  {target:'PCP_NAME',type:'null',value:''},
  {target:'PCP_DATE_LAST_SEEN',type:'null',value:''},
  {target:'PCP_DATE_FIRST_SEEN',type:'null',value:''},
  {target:'ENGAGED_WITH_PCP',type:'null',value:''},
  {target:'NO_OF_PCP_VISITS_SEEN_LAST12_MONTHS',type:'null',value:''},
  {target:'PCP_SOURCE',type:'null',value:''},
  {target:'ATTRIBUTED_PCP_NPI',type:'null',value:''},
  {target:'ATTRIBUTED_PCP_NAME',type:'null',value:''},
  {target:'ATTRIBUTED_PCP_DATE_LAST_SEEN',type:'null',value:''},
  {target:'ATTRIBUTED_PCP_DATE_FIRST_SEEN',type:'null',value:''},
  {target:'ENGAGED_WITH_ATTRIBUTED_PCP',type:'null',value:''},
  {target:'NO_OF_ATTRIBUTED_PCP_VISITS_SEEN_LAST12_MONTHS',type:'null',value:''},
  {target:'ATTRIBUTED_PCP_SOURCE',type:'null',value:''},
  {target:'UDF3',type:'direct',value:'CVRG_MED_IND'},
  {target:'UDF4',type:'direct',value:'CVRG_PHRM_IND'},
  {target:'UDF5',type:'direct',value:'CVRG_DENT_IND'},
];
