export const ELIG_RAW_FIELDS = [
  'CHNL_SRC_CD','LGCY_MBR_NUM','CUST_LAST_NM','CUST_FRST_NM','CUST_BRTH_DT','CUST_GENDR_CD',
  'CIGNA_RELSHP_CD','CLIENT_ACCT_NUM','ELGBTY_BRNCH_NUM','BEN_OPT_CD','CUST_ELGBTY_CVRG_EFF_DT',
  'CUST_ELGBTY_CVRG_TERM_DT','COVERAGE_TYPE','CUST_POSTL_CD','DERV_PCP_PROV_ID','CVRG_PER_YR_MTH_NUM',
  'AMI','INDIV_ENTPR_ID','DERV_SRC_SYS_CD','ACCT_TY_CD','CLIENT_ID','CUST_AGE_NUM','AGE_BAND_CD',
  'NT_ID','RT_REGN_CD','CVRG_PHRM_IND','MEDCR_AS_PRIM_IND','CUST_ADDR_LN_1','CUST_ADDR_LN_2',
  'CUST_CITY_NM','CUST_ST_CD','CVRG_MED_IND','CVRG_DENT_IND','CVRG_BEHVRAL_IND','CVRG_VSN_IND',
  'SUBSCRBR_STAT_CD','SUBGRP_ID','BEN_PLAN_NUM','SOURCEFILENAME','FILE_RECEIVED_DATE','IMPORT_DATE'
];

/**
 * MAP_MEMBER_PLATFORM: same pattern as pharmacy/medical — type/value build STAGING from RECEIVED_RAW
 * (direct = raw column name, expression = SQL over raw columns).
 * Optional insertExpr: SQL for final INSERT when it must differ (joins to B=ZIP, C=client group, or ARRAY logic).
 * If insertExpr is blank, INSERT uses A.<target> (or NULL if type is null).
 */
export const ELIG_MEMBER_PLATFORM_DEFAULTS = [
  { target: 'CH_MEMBER_ID', type: 'null', value: '' },
  { target: 'CH_EMPLOYER_ID', type: 'null', value: '', insertExpr: "COALESCE(C.CH_EMPLOYER_ID, '802')" },
  { target: 'MEMBER_ID', type: 'direct', value: 'LGCY_MBR_NUM' },
  { target: 'GROUP_ID', type: 'direct', value: 'CLIENT_ACCT_NUM' },
  { target: 'EMPLOYEE_ID', type: 'expression', value: 'LEFT(LGCY_MBR_NUM, LENGTH(LGCY_MBR_NUM) - 1)' },
  { target: 'FIRST_NAME', type: 'direct', value: 'CUST_FRST_NM' },
  { target: 'MIDDLE_NAME', type: 'null', value: '' },
  { target: 'LAST_NAME', type: 'direct', value: 'CUST_LAST_NM' },
  { target: 'SSN', type: 'null', value: '', insertExpr: 'COALESCE(A.SSN, LEFT(A.MEMBER_ID, 9))' },
  { target: 'GENDER', type: 'direct', value: 'CUST_GENDR_CD' },
  { target: 'DOB', type: 'expression', value: "TO_DATE(CUST_BRTH_DT,'YYYYMMDD')" },
  { target: 'ADDRESS_1', type: 'direct', value: 'CUST_ADDR_LN_1', insertExpr: 'UPPER(A.ADDRESS_1)' },
  { target: 'ADDRESS_2', type: 'direct', value: 'CUST_ADDR_LN_2', insertExpr: 'UPPER(A.ADDRESS_2)' },
  { target: 'CITY', type: 'direct', value: 'CUST_CITY_NM', insertExpr: 'UPPER(COALESCE(A.CITY, B.CITY))' },
  { target: 'COUNTY', type: 'null', value: '', insertExpr: 'UPPER(B.COUNTY)' },
  { target: 'STATE', type: 'direct', value: 'CUST_ST_CD', insertExpr: 'UPPER(COALESCE(A.STATE, B.STATE))' },
  { target: 'ZIP_CODE', type: 'direct', value: 'CUST_POSTL_CD' },
  { target: 'MARITAL_STATUS', type: 'null', value: '' },
  { target: 'RACE', type: 'null', value: '' },
  { target: 'ETHNIC_GROUP', type: 'null', value: '' },
  { target: 'EDUCATION_LEVEL', type: 'null', value: '' },
  { target: 'RELATIONSHIP', type: 'expression', value: "CASE WHEN CIGNA_RELSHP_CD='EE' THEN 'EMPLOYEE' WHEN CIGNA_RELSHP_CD='SP' THEN 'SPOUSE' WHEN CIGNA_RELSHP_CD='CH' THEN 'DEPENDENT' ELSE CIGNA_RELSHP_CD END" },
  { target: 'EFFECTIVE_DATE', type: 'expression', value: "TO_DATE(NULLIF(TRIM(CUST_ELGBTY_CVRG_EFF_DT),''),'YYYYMMDD')" },
  { target: 'TERMINATION_DATE', type: 'expression', value: "TO_DATE(NULLIF(TRIM(CUST_ELGBTY_CVRG_TERM_DT),''),'YYYYMMDD')" },
  { target: 'AGE_RANGE', type: 'direct', value: 'AGE_BAND_CD' },
  { target: 'OFFICE_LOCATION', type: 'null', value: '' },
  { target: 'ALTERNATE_MEMBER_ID', type: 'direct', value: 'AMI' },
  { target: 'PHONE_HOME', type: 'null', value: '' },
  { target: 'PHONE_WORK', type: 'null', value: '' },
  { target: 'PHONE_MOBILE', type: 'null', value: '' },
  { target: 'EMAIL_ADDRESS_HOME', type: 'null', value: '' },
  { target: 'EMAIL_ADDRESS_WORK', type: 'null', value: '' },
  { target: 'MEMBER_STATUS', type: 'direct', value: 'SUBSCRBR_STAT_CD' },
  { target: 'PHS_REVIEWED', type: 'null', value: '' },
  { target: 'ENGAGED', type: 'null', value: '' },
  { target: 'MERGE_DT', type: 'null', value: '' },
  { target: 'MERGED_INTO', type: 'null', value: '' },
  { target: 'PHA_ENGAGEMENT_DATE', type: 'null', value: '' },
  { target: 'CC_ENGAGEMENT_DATE', type: 'null', value: '' },
  { target: 'PROGRAM_TYPE_ID', type: 'null', value: '' },
  { target: 'FIRST_NAME_EDITED', type: 'null', value: '' },
  { target: 'MIDDLE_NAME_EDITED', type: 'null', value: '' },
  { target: 'LAST_NAME_EDITED', type: 'null', value: '' },
  { target: 'GENDER_EDITED', type: 'null', value: '' },
  { target: 'ADDRESS_1_EDITED', type: 'null', value: '' },
  { target: 'ADDRESS_2_EDITED', type: 'null', value: '' },
  { target: 'CITY_EDITED', type: 'null', value: '' },
  { target: 'STATE_EDITED', type: 'null', value: '' },
  { target: 'ZIP_CODE_EDITED', type: 'null', value: '' },
  { target: 'EMAIL_ADDRESS_EDITED', type: 'null', value: '' },
  { target: 'CELL_PHONE_EDITED', type: 'null', value: '' },
  { target: 'WORK_PHONE_EDITED', type: 'null', value: '' },
  { target: 'HOME_PHONE_EDITED', type: 'null', value: '' },
  { target: 'ETHNIC_GROUP_EDITED', type: 'null', value: '' },
  { target: 'USER_LAST_EDITED_BY_ID', type: 'null', value: '' },
  { target: 'LAST_EDITED_TIMESTAMP', type: 'null', value: '' },
  { target: 'UDF1', type: 'direct', value: 'INDIV_ENTPR_ID' },
  { target: 'UDF2', type: 'direct', value: 'DERV_PCP_PROV_ID' },
  { target: 'SOURCEFILENAME', type: 'direct', value: 'SOURCEFILENAME' },
  { target: 'RECEIVED_DATE', type: 'direct', value: 'FILE_RECEIVED_DATE' },
  { target: 'IMPORT_DATE', type: 'direct', value: 'IMPORT_DATE' },
  { target: 'SCRUBBED_DATE', type: 'null', value: '', insertExpr: 'CURRENT_DATE()' },
  { target: 'DATA_SOURCE', type: 'hardcoded', value: 'ELIGIBILITY' },
  { target: 'JOB_TITLE', type: 'null', value: '' },
  { target: 'INCOME_LEVEL', type: 'null', value: '' },
  { target: 'BUSINESS_UNIT', type: 'null', value: '' },
  { target: 'EMPLOYEE_SSN', type: 'null', value: '' },
  { target: 'EMPLOYEE_FIRST_NAME', type: 'null', value: '' },
  { target: 'EMPLOYEE_MIDDLE_NAME', type: 'null', value: '' },
  { target: 'EMPLOYEE_LAST_NAME', type: 'null', value: '' },
  { target: 'PCP_NPI', type: 'null', value: '' },
  { target: 'PCP_NAME', type: 'null', value: '' },
  { target: 'PCP_DATE_LAST_SEEN', type: 'null', value: '' },
  { target: 'PCP_DATE_FIRST_SEEN', type: 'null', value: '' },
  { target: 'ENGAGED_WITH_PCP', type: 'null', value: '' },
  { target: 'NO_OF_PCP_VISITS_SEEN_LAST12_MONTHS', type: 'null', value: '' },
  { target: 'PCP_SOURCE', type: 'null', value: '' },
  { target: 'ATTRIBUTED_PCP_NPI', type: 'null', value: '' },
  { target: 'ATTRIBUTED_PCP_NAME', type: 'null', value: '' },
  { target: 'ATTRIBUTED_PCP_DATE_LAST_SEEN', type: 'null', value: '' },
  { target: 'ATTRIBUTED_PCP_DATE_FIRST_SEEN', type: 'null', value: '' },
  { target: 'ENGAGED_WITH_ATTRIBUTED_PCP', type: 'null', value: '' },
  { target: 'NO_OF_ATTRIBUTED_PCP_VISITS_SEEN_LAST12_MONTHS', type: 'null', value: '' },
  { target: 'ATTRIBUTED_PCP_SOURCE', type: 'null', value: '' },
  { target: 'UDF3', type: 'direct', value: 'CVRG_MED_IND', insertExpr: 'TO_VARCHAR(A.MEMBER_ID_2)' },
  { target: 'UDF4', type: 'direct', value: 'CVRG_PHRM_IND' },
  { target: 'UDF5', type: 'direct', value: 'CVRG_DENT_IND' },
];

/** INSERT INTO MAP_ELIGIBILITY_PLATFORM — A = latest row, B = enrollment, C = master client group. */
export const ELIG_ELIGIBILITY_PLATFORM_DEFAULTS = [
  { target: 'CH_ELIGIBILITY_ID', type: 'null', value: '' },
  { target: 'RECORD_ID', type: 'null', value: '' },
  { target: 'CH_MEMBER_ID', type: 'null', value: '' },
  { target: 'CH_EMPLOYER_ID', type: 'expression', value: "COALESCE(C.CH_EMPLOYER_ID, '802')" },
  { target: 'MEMBER_ID', type: 'expression', value: 'A.MEMBER_ID' },
  { target: 'GROUP_ID', type: 'expression', value: 'A.GROUP_ID' },
  { target: 'EMPLOYEE_ID', type: 'expression', value: 'A.EMPLOYEE_ID' },
  { target: 'POLICY_ID', type: 'hardcoded', value: 'BK' },
  { target: 'PLAN_TYPE', type: 'null', value: '' },
  { target: 'CARRIER_ID', type: 'hardcoded', value: 'CIGNA' },
  { target: 'CARRIER_NAME', type: 'hardcoded', value: 'CIGNA' },
  { target: 'COVERAGE_TYPE', type: 'null', value: '' },
  { target: 'PLAN_ID', type: 'expression', value: 'A.GROUP_ID' },
  { target: 'PLAN_NAME', type: 'expression', value: 'A.GROUP_ID' },
  { target: 'BENEFIT_TYPE', type: 'hardcoded', value: 'Medical' },
  { target: 'EFFECTIVE_DATE', type: 'expression', value: 'B.EFFECTIVE_DATE' },
  { target: 'TERMINATION_DATE', type: 'expression', value: 'B.TERMINATION_DATE' },
  { target: 'MERGE_DT', type: 'null', value: '' },
  { target: 'MERGED_FROM_CH_MEMBER_ID', type: 'null', value: '' },
  { target: 'MERGED_FROM_MEMBER_ID', type: 'null', value: '' },
  { target: 'SOURCEFILENAME', type: 'expression', value: 'A.SOURCEFILENAME' },
  { target: 'RECEIVED_DATE', type: 'expression', value: 'A.RECEIVED_DATE' },
  { target: 'IMPORT_DATE', type: 'expression', value: 'A.IMPORT_DATE' },
  { target: 'SCRUBBED_DATE', type: 'expression', value: 'CURRENT_DATE()' },
  { target: 'DATA_SOURCE', type: 'expression', value: 'A.DATA_SOURCE' },
  { target: 'FIRST_NAME', type: 'expression', value: 'A.FIRST_NAME' },
  { target: 'LAST_NAME', type: 'expression', value: 'A.LAST_NAME' },
  { target: 'DOB', type: 'expression', value: 'A.DOB' },
  { target: 'GENDER', type: 'expression', value: 'A.GENDER' },
  { target: 'UDF1', type: 'expression', value: 'A.UDF1' },
  { target: 'UDF2', type: 'expression', value: 'A.UDF2' },
  { target: 'UDF3', type: 'expression', value: 'A.UDF3' },
  { target: 'UDF4', type: 'expression', value: 'A.UDF4' },
  { target: 'UDF5', type: 'expression', value: 'A.UDF5' },
];
