export const MED_MAX_FIELDS = new Set(['SOURCEFILENAME','FILE_RECEIVED_DATE','IMPORT_DATE']);
// Fields aliased in dedup: SVC_MINR_CD_1 → AS SVC_MINR_CD
export const MED_FIELD_ALIAS = { 'SVC_MINR_CD_1': 'SVC_MINR_CD' };
// Hardcoded '0.00' values injected into dedup (not from raw)
export const MED_HARDCODED_DEDUP = ['DERV_COINS_AMT','DERV_COPAY_AMT','DERV_DDCTBL_AMT','DERV_COB_CIGNA_SAVE_AMT'];

export const MED_RAW_FIELDS = [
  'CHNL_SRC_CD','CLIENT_ACCT_NUM','CLIENT_ID','HMO_CD','ELGBTY_BRNCH_NUM','BEN_PLAN_NUM',
  'ACCT_TY_CD','ACCT_SUBTY_CD','PRODT_TY_CD','RNDR_PROV_ADDR_LN_1','RNDR_PROV_ADDR_LN_2',
  'LGCY_MBR_NUM','PATNT_FRST_NM','PATNT_LAST_NM','PATNT_BRTH_DT','PATNT_GENDR_CD',
  'PATNT_ST_CD','PATNT_POSTL_CD','PATNT_AGE_NUM','PATNT_RELSHP_CD','SUBSCRBR_STAT_CD',
  'RNDR_PROV_CITY_NM','RNDR_PROV_ST_CD','RNDR_PROV_ID','BILL_PROV_TIN','BILL_PROV_NPI',
  'BILL_PROV_NM','BILL_PROV_ADDR_LN_1','BILL_PROV_ADDR_LN_2','BILL_PROV_CITY_NM',
  'BILL_PROV_ST_CD','BILL_PROV_POSTL_CD','RNDR_PROV_TY_CD','RNDR_PROV_SPECLTY_CD',
  'PROV_PARTCPNT_AGRMT_CD','RNDR_PROV_NM','RNDR_PROV_POSTL_CD','PD_DT','SVC_BEG_DT',
  'SVC_END_DT','CLM_SYS_RECV_DT','DERV_PAYBL_AMT',
  'PROC_CD_MOD_CD_1','PROC_CD_MOD_CD_2','PROC_CD_MOD_CD_3','PROC_CD_MOD_CD_4',
  ...Array.from({length:25},(_,i)=>`CLM_DIAG_CD_${i+1}`),
  ...Array.from({length:25},(_,i)=>`CLM_POA_CD_${i+1}`),
  'CLM_SYS_CLM_ID','SVC_LN_NUM','PROC_TY_CD','PROC_CD','REVNU_CD','BEN_NT_LVL_CD',
  'MDC_CD','DERV_SU_CNT','CLM_EVENT_KEY','SRC_SVC_RMK_CD','LN_PROCS_EVENT_CD',
  'NT_ID','RNDR_PROV_NT_ID','SVC_MINR_CD_1','DERV_POS_CD','COB_INVLVMT_CD',
  'SURCHRG_ST_CD','TY_OF_BILL_CD','ENCNTR_TY_CD','ACTL_LOS_DAYS_NUM','DRG_CD',
  'DISCHRG_STAT_CD','MSC_CD','SVC_MAJ_CD','SVC_MINR_CD_2','RNDR_PROV_NPI',
  'ICD_VRSN_CD','CLM_EVENT_DRG_CD','NDC','AMI','INDIV_ENTPR_ID','REFRL_PROV_NPI',
  'SU_CNT','NEW_CLM_SYS_CLM_ID',
  ...Array.from({length:5},(_,i)=>`ICD_PROC_CD_${i+1}`),
  ...Array.from({length:19},(_,i)=>`FILLER${i+1}`),
  'SOURCEFILENAME','FILE_RECEIVED_DATE','IMPORT_DATE'
];

export const MED_STAGE_DDL = [
  'CH_MEDICAL_CLAIM_ID VARCHAR(16777216)','RECORD_ID VARCHAR(16777216)',
  'MEMBER_ID VARCHAR(16777216)','GROUP_ID VARCHAR(16777216)',
  'CH_MEMBER_ID VARCHAR(16777216)','CH_EMPLOYER_ID VARCHAR(16777216)',
  'CLAIM_ID VARCHAR(16777216)','CLAIM_LINE_ID VARCHAR(16777216)',
  'SERVICE_PROVIDER_ID VARCHAR(16777216)','PROVIDER_NPI VARCHAR(16777216)',
  'FACILITY_NPI VARCHAR(16777216)','BILLING_PROVIDER_NPI VARCHAR(16777216)',
  'PROVIDER_TIN VARCHAR(16777216)','PROVIDER_TYPE VARCHAR(16777216)',
  'PROVIDER_FIRST_NAME VARCHAR(16777216)','PROVIDER_MIDDLE_NAME VARCHAR(16777216)',
  'PROVIDER_LAST_NAME VARCHAR(16777216)','PROVIDER_NAME VARCHAR(16777216)',
  'PROVIDER_SPECIALTY_1_CODE VARCHAR(16777216)','PROVIDER_SPECIALTY_1_DESCRIPTION VARCHAR(16777216)',
  'PROVIDER_SPECIALTY_2_CODE VARCHAR(16777216)','PROVIDER_SPECIALTY_2_DESCRIPTION VARCHAR(16777216)',
  'PROVIDER_SPECIALTY_3_CODE VARCHAR(16777216)','PROVIDER_SPECIALTY_3_DESCRIPTION VARCHAR(16777216)',
  'PROVIDER_ADDRESS_1 VARCHAR(16777216)','PROVIDER_ADDRESS_2 VARCHAR(16777216)',
  'PROVIDER_CITY VARCHAR(16777216)','PROVIDER_COUNTY VARCHAR(16777216)',
  'PROVIDER_STATE VARCHAR(16777216)','PROVIDER_ZIP_CODE VARCHAR(16777216)',
  'PLACE_OF_SERVICE_CODE VARCHAR(16777216)','PLACE_OF_SERVICE_DESCRIPTION VARCHAR(16777216)',
  'DIAGNOSIS_TYPE VARCHAR(16777216)','ADMITTING_DIAGNOSIS_CODE VARCHAR(16777216)',
  'ADMITTING_DIAGNOSIS_DESCRIPTION VARCHAR(16777216)',
  ...Array.from({length:25},(_,i)=>`DIAGNOSIS_${i+1}_CODE VARCHAR(16777216),DIAGNOSIS_${i+1}_DESCRIPTION VARCHAR(16777216)`),
  'PROCEDURE_TYPE VARCHAR(16777216)','PROCEDURE_CODE VARCHAR(16777216)',
  'PROCEDURE_DESCRIPTION VARCHAR(16777216)','REVENUE_CODE VARCHAR(16777216)',
  'REVENUE_DESCRIPTION VARCHAR(16777216)','CPT_CODE VARCHAR(16777216)',
  'CPT_DESCRIPTION VARCHAR(16777216)','CPT_LONG_DESCRIPTION VARCHAR(16777216)',
  'ICD_PROCEDURE_1_CODE VARCHAR(16777216)','ICD_PROCEDURE_1_DESCRIPTION VARCHAR(16777216)',
  'ICD_PROCEDURE_2_CODE VARCHAR(16777216)','ICD_PROCEDURE_2_DESCRIPTION VARCHAR(16777216)',
  'DRG_TYPE_CODE VARCHAR(16777216)','DRG_TYPE_DESCRIPTION VARCHAR(16777216)',
  'DRG_CODE VARCHAR(16777216)','DRG_DESCRIPTION VARCHAR(16777216)',
  'HCPCS_CODE VARCHAR(16777216)','HCPCS_DESCRIPTION VARCHAR(16777216)',
  'HCPCS_LONG_DESCRIPTION VARCHAR(16777216)',
  'PROCEDURE_MODIFIER_1_CODE VARCHAR(16777216)','PROCEDURE_MODIFIER_1_DESCRIPTION VARCHAR(16777216)',
  'PROCEDURE_MODIFIER_2_CODE VARCHAR(16777216)','PROCEDURE_MODIFIER_2_DESCRIPTION VARCHAR(16777216)',
  'PROCEDURE_MODIFIER_3_CODE VARCHAR(16777216)','PROCEDURE_MODIFIER_3_DESCRIPTION VARCHAR(16777216)',
  'ADMISSION_TYPE VARCHAR(16777216)','SERVICE_FROM_DATE DATE','SERVICE_TO_DATE DATE',
  'ADJUDICATION_DATE DATE','PAID_DATE DATE','BENEFIT_CODE VARCHAR(16777216)',
  'BENEFIT_DESCRIPTION VARCHAR(16777216)','ALLOWED_AMOUNT FLOAT','BILLED_AMOUNT FLOAT',
  'COB_PAID_AMOUNT FLOAT','COINSURANCE_AMOUNT FLOAT','COPAY_AMOUNT FLOAT',
  'DEDUCTIBLE_AMOUNT FLOAT','NOT_COVERED_AMOUNT FLOAT','OTHER_SAVINGS FLOAT',
  'DISCOUNT_AMOUNT FLOAT','PAID_AMOUNT FLOAT','PAYMENT_TYPE VARCHAR(16777216)',
  'CHECK_NUMBER VARCHAR(16777216)','ORIGINAL_CLAIM_ID VARCHAR(16777216)',
  'MERGE_DT DATE','MERGED_FROM_CH_MEMBER_ID VARCHAR(16777216)',
  'MERGED_FROM_MEMBER_ID VARCHAR(16777216)','SOURCEFILENAME VARCHAR(16777216)',
  'RECEIVED_DATE DATE','IMPORT_DATE DATE','SCRUBBED_DATE DATE',
  'TYPE_OF_BILL VARCHAR(16777216)','CLAIM_NETWORK_TYPE VARCHAR(16777216)',
  'DISCHARGE_STATUS VARCHAR(16777216)','ADMIT_DATE DATE','DISCHARGE_DATE DATE',
  'UNITS_QUANTITY VARCHAR(16777216)','PLAN_PAID_AMOUNT FLOAT','MEMBER_PAID_AMOUNT FLOAT',
  'UDF1 VARCHAR(16777216)','UDF2 VARCHAR(16777216)','UDF3 VARCHAR(16777216)',
  'UDF4 VARCHAR(16777216)','UDF5 VARCHAR(16777216)','UDF6 VARCHAR(16777216)',
  'UDF7 VARCHAR(16777216)','UDF8 VARCHAR(16777216)','UDF9 VARCHAR(16777216)',
  'UDF10 VARCHAR(16777216)'
];

export const MED_DEFAULTS = [
  {target:'CH_MEDICAL_CLAIM_ID',type:'null',value:''},
  {target:'RECORD_ID',type:'null',value:''},
  {target:'MEMBER_ID',type:'direct',value:'LGCY_MBR_NUM'},
  {target:'GROUP_ID',type:'direct',value:'CLIENT_ACCT_NUM'},
  {target:'CH_MEMBER_ID',type:'null',value:''},
  {target:'CH_EMPLOYER_ID',type:'hardcoded',value:'802'},
  {target:'CLAIM_ID',type:'direct',value:'CLM_SYS_CLM_ID'},
  {target:'CLAIM_LINE_ID',type:'direct',value:'SVC_LN_NUM'},
  {target:'SERVICE_PROVIDER_ID',type:'direct',value:'RNDR_PROV_ID'},
  {target:'PROVIDER_NPI',type:'expression',value:"COALESCE(LPAD(RNDR_PROV_NPI,10,'0'),LPAD(BILL_PROV_NPI,10,'0'),LPAD(REFRL_PROV_NPI,10,'0'))"},
  {target:'FACILITY_NPI',type:'null',value:''},
  {target:'BILLING_PROVIDER_NPI',type:'expression',value:"COALESCE(LPAD(BILL_PROV_NPI,10,'0'),LPAD(RNDR_PROV_NPI,10,'0'))"},
  {target:'PROVIDER_TIN',type:'direct',value:'BILL_PROV_TIN'},
  {target:'PROVIDER_TYPE',type:'null',value:''},
  {target:'PROVIDER_FIRST_NAME',type:'null',value:''},
  {target:'PROVIDER_MIDDLE_NAME',type:'null',value:''},
  {target:'PROVIDER_LAST_NAME',type:'null',value:''},
  {target:'PROVIDER_NAME',type:'null',value:''},
  {target:'PROVIDER_SPECIALTY_1_CODE',type:'null',value:''},
  {target:'PROVIDER_SPECIALTY_1_DESCRIPTION',type:'null',value:''},
  {target:'PROVIDER_SPECIALTY_2_CODE',type:'null',value:''},
  {target:'PROVIDER_SPECIALTY_2_DESCRIPTION',type:'null',value:''},
  {target:'PROVIDER_SPECIALTY_3_CODE',type:'null',value:''},
  {target:'PROVIDER_SPECIALTY_3_DESCRIPTION',type:'null',value:''},
  {target:'PROVIDER_ADDRESS_1',type:'null',value:''},
  {target:'PROVIDER_ADDRESS_2',type:'null',value:''},
  {target:'PROVIDER_CITY',type:'null',value:''},
  {target:'PROVIDER_COUNTY',type:'null',value:''},
  {target:'PROVIDER_STATE',type:'null',value:''},
  {target:'PROVIDER_ZIP_CODE',type:'null',value:''},
  {target:'PLACE_OF_SERVICE_CODE',type:'expression',value:"LPAD(TRIM(REGEXP_REPLACE(DERV_POS_CD,'[^0-9]', '')),2,'0')"},
  {target:'PLACE_OF_SERVICE_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_TYPE',type:'null',value:''},
  {target:'ADMITTING_DIAGNOSIS_CODE',type:'null',value:''},
  {target:'ADMITTING_DIAGNOSIS_DESCRIPTION',type:'null',value:''},
  ...Array.from({length:25},(_,i)=>([
    {target:`DIAGNOSIS_${i+1}_CODE`,type:'expression',value:`TRIM(REGEXP_REPLACE(CLM_DIAG_CD_${i+1}, '[^A-Za-z0-9]', ''))`},
    {target:`DIAGNOSIS_${i+1}_DESCRIPTION`,type:'null',value:''},
  ])).flat(),
  {target:'PROCEDURE_TYPE',type:'expression',value:"CASE WHEN PROC_TY_CD = 'CP' THEN 'CPT4' WHEN PROC_TY_CD = 'HC' THEN 'HCPCS' WHEN PROC_TY_CD = 'AD' THEN 'CDT' ELSE PROC_TY_CD END"},
  {target:'PROCEDURE_CODE',type:'direct',value:'PROC_CD'},
  {target:'PROCEDURE_DESCRIPTION',type:'null',value:''},
  {target:'REVENUE_CODE',type:'expression',value:"'R'||REGEXP_REPLACE(TRIM(REVNU_CD), '^0', '')"},
  {target:'REVENUE_DESCRIPTION',type:'null',value:''},
  {target:'CPT_CODE',type:'expression',value:"CASE WHEN PROC_TY_CD = 'CP' AND LENGTH(TRIM(REGEXP_REPLACE(PROC_CD, '[^A-Za-z0-9]', ''))) = '5' AND REGEXP_LIKE(TRIM(REGEXP_REPLACE(PROC_CD, '[^A-Za-z0-9]', '')), '^[0-9]{4}[A-Za-z]$|^[0-9]{5}$') THEN TRIM(REGEXP_REPLACE(PROC_CD, '[^A-Za-z0-9]', '')) ELSE NULL END"},
  {target:'CPT_DESCRIPTION',type:'null',value:''},
  {target:'CPT_LONG_DESCRIPTION',type:'null',value:''},
  {target:'ICD_PROCEDURE_1_CODE',type:'expression',value:'COALESCE(ICD_PROC_CD_1,ICD_PROC_CD_2,ICD_PROC_CD_3,ICD_PROC_CD_4,ICD_PROC_CD_5)'},
  {target:'ICD_PROCEDURE_1_DESCRIPTION',type:'null',value:''},
  {target:'ICD_PROCEDURE_2_CODE',type:'expression',value:'COALESCE(ICD_PROC_CD_2,ICD_PROC_CD_3,ICD_PROC_CD_4,ICD_PROC_CD_5)'},
  {target:'ICD_PROCEDURE_2_DESCRIPTION',type:'null',value:''},
  {target:'DRG_TYPE_CODE',type:'null',value:''},
  {target:'DRG_TYPE_DESCRIPTION',type:'null',value:''},
  {target:'DRG_CODE',type:'direct',value:'DRG_CD'},
  {target:'DRG_DESCRIPTION',type:'null',value:''},
  {target:'HCPCS_CODE',type:'expression',value:"CASE WHEN PROC_TY_CD = 'HC' AND LENGTH(TRIM(REGEXP_REPLACE(PROC_CD, '[^A-Za-z0-9]', ''))) = '5' AND REGEXP_LIKE(TRIM(REGEXP_REPLACE(PROC_CD, '[^A-Za-z0-9]', '')), '^[A-Za-z][0-9]{4}$') THEN TRIM(REGEXP_REPLACE(PROC_CD, '[^A-Za-z0-9]', '')) ELSE NULL END"},
  {target:'HCPCS_DESCRIPTION',type:'null',value:''},
  {target:'HCPCS_LONG_DESCRIPTION',type:'null',value:''},
  {target:'PROCEDURE_MODIFIER_1_CODE',type:'expression',value:'COALESCE(PROC_CD_MOD_CD_1,PROC_CD_MOD_CD_2,PROC_CD_MOD_CD_3,PROC_CD_MOD_CD_4)'},
  {target:'PROCEDURE_MODIFIER_1_DESCRIPTION',type:'null',value:''},
  {target:'PROCEDURE_MODIFIER_2_CODE',type:'expression',value:'COALESCE(PROC_CD_MOD_CD_2,PROC_CD_MOD_CD_3,PROC_CD_MOD_CD_4)'},
  {target:'PROCEDURE_MODIFIER_2_DESCRIPTION',type:'null',value:''},
  {target:'PROCEDURE_MODIFIER_3_CODE',type:'expression',value:'COALESCE(PROC_CD_MOD_CD_3,PROC_CD_MOD_CD_4)'},
  {target:'PROCEDURE_MODIFIER_3_DESCRIPTION',type:'null',value:''},
  {target:'ADMISSION_TYPE',type:'null',value:''},
  {target:'SERVICE_FROM_DATE',type:'expression',value:"TO_DATE(SVC_BEG_DT,'YYYYMMDD')"},
  {target:'SERVICE_TO_DATE',type:'expression',value:"TO_DATE(SVC_END_DT,'YYYYMMDD')"},
  {target:'ADJUDICATION_DATE',type:'null',value:''},
  {target:'PAID_DATE',type:'expression',value:"TO_DATE(PD_DT,'YYYYMMDD')"},
  {target:'BENEFIT_CODE',type:'null',value:''},
  {target:'BENEFIT_DESCRIPTION',type:'null',value:''},
  {target:'ALLOWED_AMOUNT',type:'expression',value:"IFNULL(DERV_COINS_AMT::FLOAT,'0.00')+IFNULL(DERV_COPAY_AMT::FLOAT,'0.00')+IFNULL(DERV_DDCTBL_AMT::FLOAT,'0.00')+IFNULL(DERV_PAYBL_AMT::FLOAT,'0.00')"},
  {target:'BILLED_AMOUNT',type:'expression',value:"IFNULL(DERV_COINS_AMT::FLOAT,'0.00')+IFNULL(DERV_COPAY_AMT::FLOAT,'0.00')+IFNULL(DERV_DDCTBL_AMT::FLOAT,'0.00')+IFNULL(DERV_PAYBL_AMT::FLOAT,'0.00')"},
  {target:'COB_PAID_AMOUNT',type:'null',value:''},
  {target:'COINSURANCE_AMOUNT',type:'expression',value:"IFNULL(DERV_COINS_AMT::FLOAT,'0.00')"},
  {target:'COPAY_AMOUNT',type:'expression',value:"IFNULL(DERV_COPAY_AMT::FLOAT,'0.00')"},
  {target:'DEDUCTIBLE_AMOUNT',type:'expression',value:"IFNULL(DERV_DDCTBL_AMT::FLOAT,'0.00')"},
  {target:'NOT_COVERED_AMOUNT',type:'null',value:''},
  {target:'OTHER_SAVINGS',type:'expression',value:"IFNULL(DERV_COB_CIGNA_SAVE_AMT::FLOAT,'0.00')"},
  {target:'DISCOUNT_AMOUNT',type:'null',value:''},
  {target:'PAID_AMOUNT',type:'expression',value:"IFNULL(DERV_COINS_AMT::FLOAT,'0.00')+IFNULL(DERV_COPAY_AMT::FLOAT,'0.00')+IFNULL(DERV_DDCTBL_AMT::FLOAT,'0.00')+IFNULL(DERV_PAYBL_AMT::FLOAT,'0.00')"},
  {target:'PAYMENT_TYPE',type:'null',value:''},
  {target:'CHECK_NUMBER',type:'null',value:''},
  {target:'ORIGINAL_CLAIM_ID',type:'null',value:''},
  {target:'MERGE_DT',type:'null',value:''},
  {target:'MERGED_FROM_CH_MEMBER_ID',type:'null',value:''},
  {target:'MERGED_FROM_MEMBER_ID',type:'null',value:''},
  {target:'SOURCEFILENAME',type:'direct',value:'SOURCEFILENAME'},
  {target:'RECEIVED_DATE',type:'direct',value:'FILE_RECEIVED_DATE'},
  {target:'IMPORT_DATE',type:'direct',value:'IMPORT_DATE'},
  {target:'SCRUBBED_DATE',type:'expression',value:'CURRENT_DATE()'},
  {target:'TYPE_OF_BILL',type:'direct',value:'TY_OF_BILL_CD'},
  {target:'CLAIM_NETWORK_TYPE',type:'expression',value:"CASE WHEN BEN_NT_LVL_CD = 'INNT' THEN 'IN-NETWORK' WHEN BEN_NT_LVL_CD = 'OUTNT' THEN 'OUT-NETWORK' WHEN BEN_NT_LVL_CD = 'INDEM' THEN 'INDEMITY' END"},
  {target:'DISCHARGE_STATUS',type:'direct',value:'DISCHRG_STAT_CD'},
  {target:'ADMIT_DATE',type:'null',value:''},
  {target:'DISCHARGE_DATE',type:'null',value:''},
  {target:'UNITS_QUANTITY',type:'direct',value:'SU_CNT'},
  {target:'PLAN_PAID_AMOUNT',type:'expression',value:"IFNULL(DERV_PAYBL_AMT::FLOAT,'0.00')"},
  {target:'MEMBER_PAID_AMOUNT',type:'expression',value:"IFNULL(DERV_COINS_AMT::FLOAT,'0.00')+IFNULL(DERV_COPAY_AMT::FLOAT,'0.00')+IFNULL(DERV_DDCTBL_AMT::FLOAT,'0.00')"},
  {target:'UDF1',type:'expression',value:"IFNULL(PATNT_FRST_NM,'X')||'_'||IFNULL(PATNT_LAST_NM,'X')||'_'||COALESCE(TO_DATE(PATNT_BRTH_DT,'YYYYMMDD'),'99991231')||'_'||IFNULL(PATNT_GENDR_CD,'U')||'_'||IFNULL(AMI,'X')||'_'||IFNULL(PATNT_RELSHP_CD,'X')||'_'||IFNULL(INDIV_ENTPR_ID,'X')"},
  {target:'UDF2',type:'null',value:''},
  {target:'UDF3',type:'null',value:''},
  {target:'UDF4',type:'null',value:''},
  {target:'UDF5',type:'null',value:''},
  {target:'UDF6',type:'direct',value:'ACCT_TY_CD'},
  {target:'UDF7',type:'direct',value:'NEW_CLM_SYS_CLM_ID'},
  {target:'UDF8',type:'direct',value:'LN_PROCS_EVENT_CD'},
  {target:'UDF9',type:'direct',value:'CLM_EVENT_KEY'},
  {target:'UDF10',type:'direct',value:'BEN_NT_LVL_CD'},
];


export const AETNA_MED_DEFAULTS = [
  {target:'CH_MEDICAL_CLAIM_ID',type:'null',value:''},
  {target:'RECORD_ID',type:'null',value:''},
  {target:'MEMBER_ID',type:'direct',value:'MEMBER_ID'},
  {target:'GROUP_ID',type:'hardcoded',value:'2WAB'},
  {target:'CH_MEMBER_ID',type:'null',value:''},
  {target:'CH_EMPLOYER_ID',type:'hardcoded',value:'454'},
  {target:'CLAIM_ID',type:'direct',value:'SRC_CLM_ID'},
  {target:'CLAIM_LINE_ID',type:'direct',value:'SRC_CLAIM_LINE_ID'},
  {target:'SERVICE_PROVIDER_ID',type:'direct',value:'SRV_PRVDR_ID'},
  {target:'PROVIDER_NPI',type:'expression',value:"CASE WHEN LPAD(SRV_PRVDR_NPI,10,'0') = '0000000000' THEN NULL ELSE LPAD(SRV_PRVDR_NPI,10,'0') END"},
  {target:'FACILITY_NPI',type:'null',value:''},
  {target:'BILLING_PROVIDER_NPI',type:'null',value:''},
  {target:'PROVIDER_TIN',type:'direct',value:'SERV_PROV_TAX_ID_NBR'},
  {target:'PROVIDER_TYPE',type:'expression',value:"NULLIF(PROVIDER_TYPE_CD,'NA')"},
  {target:'PROVIDER_FIRST_NAME',type:'null',value:''},
  {target:'PROVIDER_MIDDLE_NAME',type:'null',value:''},
  {target:'PROVIDER_LAST_NAME',type:'null',value:''},
  {target:'PROVIDER_NAME',type:'direct',value:'SRV_PRV_PRINT_NM'},
  {target:'PROVIDER_SPECIALTY_1_CODE',type:'null',value:''},
  {target:'PROVIDER_SPECIALTY_1_DESCRIPTION',type:'null',value:''},
  {target:'PROVIDER_SPECIALTY_2_CODE',type:'null',value:''},
  {target:'PROVIDER_SPECIALTY_2_DESCRIPTION',type:'null',value:''},
  {target:'PROVIDER_SPECIALTY_3_CODE',type:'null',value:''},
  {target:'PROVIDER_SPECIALTY_3_DESCRIPTION',type:'null',value:''},
  {target:'PROVIDER_ADDRESS_1',type:'direct',value:'ADDRESS_LINE_1_TXT'},
  {target:'PROVIDER_ADDRESS_2',type:'direct',value:'ADDRESS_LINE_2_TXT'},
  {target:'PROVIDER_CITY',type:'direct',value:'CITY_NM'},
  {target:'PROVIDER_COUNTY',type:'null',value:''},
  {target:'PROVIDER_STATE',type:'direct',value:'STATE_POSTAL_CD'},
  {target:'PROVIDER_ZIP_CODE',type:'direct',value:'ZIP_CD'},
  {target:'PLACE_OF_SERVICE_CODE',type:'expression',value:"CASE WHEN HCFA_PLC_SRV_CD = 'N' THEN '99' ELSE HCFA_PLC_SRV_CD END"},
  {target:'PLACE_OF_SERVICE_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_TYPE',type:'expression',value:"CASE WHEN REGEXP_REPLACE(PRI_ICD9_DX_CD,'[^A-Za-z0-9]') IS NOT NULL THEN 'ICD10' ELSE NULL END"},
  {target:'ADMITTING_DIAGNOSIS_CODE',type:'null',value:''},
  {target:'ADMITTING_DIAGNOSIS_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_1_CODE',type:'expression',value:"REGEXP_REPLACE(PRI_ICD9_DX_CD,'[^A-Za-z0-9]')"},
  {target:'DIAGNOSIS_1_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_2_CODE',type:'expression',value:"REGEXP_REPLACE(ICD9_DX_CD_2,'[^A-Za-z0-9]')"},
  {target:'DIAGNOSIS_2_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_3_CODE',type:'expression',value:"REGEXP_REPLACE(ICD9_DX_CD_3,'[^A-Za-z0-9]')"},
  {target:'DIAGNOSIS_3_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_4_CODE',type:'expression',value:"REGEXP_REPLACE(ICD9_DX_CD_4,'[^A-Za-z0-9]')"},
  {target:'DIAGNOSIS_4_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_5_CODE',type:'expression',value:"REGEXP_REPLACE(ICD9_DX_CD_5,'[^A-Za-z0-9]')"},
  {target:'DIAGNOSIS_5_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_6_CODE',type:'expression',value:"REGEXP_REPLACE(ICD9_DX_CD_6,'[^A-Za-z0-9]')"},
  {target:'DIAGNOSIS_6_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_7_CODE',type:'expression',value:"REGEXP_REPLACE(ICD9_DX_CD_7,'[^A-Za-z0-9]')"},
  {target:'DIAGNOSIS_7_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_8_CODE',type:'expression',value:"REGEXP_REPLACE(ICD9_DX_CD_8,'[^A-Za-z0-9]')"},
  {target:'DIAGNOSIS_8_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_9_CODE',type:'expression',value:"REGEXP_REPLACE(ICD9_DX_CD_9,'[^A-Za-z0-9]')"},
  {target:'DIAGNOSIS_9_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_10_CODE',type:'expression',value:"REGEXP_REPLACE(ICD9_DX_CD_10,'[^A-Za-z0-9]')"},
  {target:'DIAGNOSIS_10_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_11_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_11_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_12_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_12_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_13_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_13_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_14_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_14_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_15_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_15_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_16_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_16_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_17_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_17_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_18_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_18_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_19_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_19_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_20_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_20_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_21_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_21_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_22_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_22_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_23_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_23_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_24_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_24_DESCRIPTION',type:'null',value:''},
  {target:'DIAGNOSIS_25_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_25_DESCRIPTION',type:'null',value:''},
  {target:'PROCEDURE_TYPE',type:'null',value:''},
  {target:'PROCEDURE_CODE',type:'expression',value:"NULLIF(LEFT(PRCDR_CD,5),'NA')"},
  {target:'PROCEDURE_DESCRIPTION',type:'null',value:''},
  {target:'REVENUE_CODE',type:'expression',value:"CASE WHEN LENGTH(REVENUE_CD) = 4 AND SUBSTR(REVENUE_CD,1,1) = '0' THEN CONCAT('R',SUBSTR(REVENUE_CD,2,3)) ELSE NULL END"},
  {target:'REVENUE_DESCRIPTION',type:'null',value:''},
  {target:'CPT_CODE',type:'expression',value:"CASE WHEN LENGTH(PRCDR_CD) = 5 AND REGEXP_LIKE(PRCDR_CD,'^[A-Za-z0-9]+$') AND REGEXP_LIKE(SUBSTR(PRCDR_CD,1,1),'^[0-9]$') THEN PRCDR_CD ELSE NULL END"},
  {target:'CPT_DESCRIPTION',type:'null',value:''},
  {target:'CPT_LONG_DESCRIPTION',type:'null',value:''},
  {target:'ICD_PROCEDURE_1_CODE',type:'expression',value:"NULLIF(ICD9_PRCDR_CD_1,'NA')"},
  {target:'ICD_PROCEDURE_1_DESCRIPTION',type:'null',value:''},
  {target:'ICD_PROCEDURE_2_CODE',type:'expression',value:"NULLIF(ICD9_PRCDR_CD_2,'NA')"},
  {target:'ICD_PROCEDURE_2_DESCRIPTION',type:'null',value:''},
  {target:'DRG_TYPE_CODE',type:'null',value:''},
  {target:'DRG_TYPE_DESCRIPTION',type:'null',value:''},
  {target:'DRG_CODE',type:'direct',value:'DRG_CD'},
  {target:'DRG_DESCRIPTION',type:'null',value:''},
  {target:'HCPCS_CODE',type:'expression',value:"CASE WHEN LENGTH(PRCDR_CD) = 5 AND REGEXP_LIKE(PRCDR_CD,'^[A-Za-z0-9]+$') AND REGEXP_LIKE(SUBSTR(PRCDR_CD,1,1),'^[A-Za-z]$') THEN PRCDR_CD ELSE NULL END"},
  {target:'HCPCS_DESCRIPTION',type:'null',value:''},
  {target:'HCPCS_LONG_DESCRIPTION',type:'null',value:''},
  {target:'PROCEDURE_MODIFIER_1_CODE',type:'expression',value:"NULLIF(NULLIF(PRCDR_MODIFIER_CD,'NA'),'')"},
  {target:'PROCEDURE_MODIFIER_1_DESCRIPTION',type:'null',value:''},
  {target:'PROCEDURE_MODIFIER_2_CODE',type:'expression',value:"NULLIF(NULLIF(PRCDR_MODIFIER_CD_2,'NA'),'')"},
  {target:'PROCEDURE_MODIFIER_2_DESCRIPTION',type:'null',value:''},
  {target:'PROCEDURE_MODIFIER_3_CODE',type:'expression',value:"NULLIF(NULLIF(PRCDR_MODIFIER_CD_3,'NA'),'')"},
  {target:'PROCEDURE_MODIFIER_3_DESCRIPTION',type:'null',value:''},
  {target:'ADMISSION_TYPE',type:'null',value:''},
  {target:'SERVICE_FROM_DATE',type:'expression',value:"TO_DATE(SRV_START_DT,'YYYY-MM-DD')"},
  {target:'SERVICE_TO_DATE',type:'expression',value:"TO_DATE(SRV_STOP_DT,'YYYY-MM-DD')"},
  {target:'ADJUDICATION_DATE',type:'expression',value:"TO_DATE(ADJN_DT,'YYYY-MM-DD')"},
  {target:'PAID_DATE',type:'expression',value:"TO_DATE(PAID_DT,'YYYY-MM-DD')"},
  {target:'BENEFIT_CODE',type:'direct',value:'BENEFIT_CD'},
  {target:'BENEFIT_DESCRIPTION',type:'null',value:''},
  {target:'ALLOWED_AMOUNT',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(ALLOWED_AMT/100,18,2))'},
  {target:'BILLED_AMOUNT',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(BILLED_AMT/100,18,2))'},
  {target:'COB_PAID_AMOUNT',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(COB_PAID_AMT/100,18,2))'},
  {target:'COINSURANCE_AMOUNT',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(COINSURANCE_AMT/100,18,2))'},
  {target:'COPAY_AMOUNT',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(SRV_COPAY_AMT/100,18,2))'},
  {target:'DEDUCTIBLE_AMOUNT',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(DEDUCTIBLE_AMT/100,18,2))'},
  {target:'NOT_COVERED_AMOUNT',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(NOT_COVERED_AMT_1/100,18,2))'},
  {target:'OTHER_SAVINGS',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(COB_SAVINGS_AMT/100,18,2))'},
  {target:'DISCOUNT_AMOUNT',type:'hardcoded',value:'0'},
  {target:'PAID_AMOUNT',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(COALESCE(PAID_AMT,0)/100+COALESCE(SRV_COPAY_AMT,0)/100+COALESCE(COINSURANCE_AMT,0)/100+COALESCE(DEDUCTIBLE_AMT,0)/100,18,2))'},
  {target:'PAYMENT_TYPE',type:'null',value:''},
  {target:'CHECK_NUMBER',type:'null',value:''},
  {target:'ORIGINAL_CLAIM_ID',type:'direct',value:'DERIVED_TCN_NBR'},
  {target:'MERGE_DT',type:'null',value:''},
  {target:'MERGED_FROM_CH_MEMBER_ID',type:'null',value:''},
  {target:'MERGED_FROM_MEMBER_ID',type:'null',value:''},
  {target:'SOURCEFILENAME',type:'direct',value:'SOURCEFILENAME'},
  {target:'RECEIVED_DATE',type:'direct',value:'FILE_RECEIVED_DATE'},
  {target:'IMPORT_DATE',type:'expression',value:'CURRENT_DATE()'},
  {target:'SCRUBBED_DATE',type:'expression',value:'CURRENT_DATE()'},
  {target:'TYPE_OF_BILL',type:'direct',value:'HCFA_BILL_TYPE_CD'},
  {target:'CLAIM_NETWORK_TYPE',type:'null',value:''},
  {target:'DISCHARGE_STATUS',type:'expression',value:"NULLIF(DSCHRG_STATUS_CD,'NA')"},
  {target:'ADMIT_DATE',type:'direct',value:'SRC_ADMIT_DT'},
  {target:'DISCHARGE_DATE',type:'direct',value:'SRC_DISCHARGE_DT'},
  {target:'UNITS_QUANTITY',type:'null',value:''},
  {target:'PLAN_PAID_AMOUNT',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(PAID_AMT/100,18,2))'},
  {target:'MEMBER_PAID_AMOUNT',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(COALESCE(SRV_COPAY_AMT,0)/100+COALESCE(COINSURANCE_AMT,0)/100+COALESCE(DEDUCTIBLE_AMT,0)/100,18,2))'},
  {target:'UDF1',type:'direct',value:'REVERSAL_CD'},
  {target:'UDF2',type:'direct',value:'MEM_FIRST_NM'},
  {target:'UDF3',type:'direct',value:'MEM_LAST_NM'},
  {target:'UDF4',type:'direct',value:'BIRTH_DT'},
  {target:'UDF5',type:'direct',value:'MBR_GENDER_CD'},
  {target:'UDF6',type:'direct',value:'MEMBER_NUMBER'},
  {target:'UDF7',type:'null',value:''},
  {target:'UDF8',type:'null',value:''},
  {target:'UDF9',type:'null',value:''},
  {target:'UDF10',type:'null',value:''},
];