export const PX_RAW_FIELDS = [
  'TRANSACTIONID','PCN','PHARMACYID','PHARMACYNAME','PHARMACYADDRESS','PHARMACYCITY',
  'PHARMACYSTATE','PHARMACYZIPCODE','PHARMACYPHONE','PHARMACYFAX','RELATIONSHIPID',
  'PHARMACYSERVICETYPE','MEMBERID','MEMBERFIRSTNAME','MEMBERLASTNAME','MEMBERGENDER',
  'BIRTHDATE','OTHERCOVERAGECODE','OTHERPAYERAMOUNT','SERVICEDATE','TRANSACTIONDATE',
  'RXNUMBER','GCN','GPICODE','TRANSTATUS','GNN','TRANCODE','COSTBASIS','NDC',
  'DRUGNAME','LABELNAME','DRUGSTRENGTH','DOSAGEFORM','GPINAME','RXOTCINDICATION',
  'UNITDOSE','COMPOUNDCODE','QUANTITYDISPENSED','DRUGTYPE','TIERCODE','SPECIALTY',
  'DAWCODE','FORMULARYINDICATOR','PRESCRIBINGPHYSICIAN','DOCTORDEA','DOCTORZIPCODE',
  'GROSSAMTDUE','USUALANDCUST','BASISPAID','INGREDIENTCOST','DISPFEEPAID','SALESTAX',
  'INCENTIVEFEE','PLANPAID','PATIENTPAID','DEDUCTIBLEAMT','OOP','COPAY','COINSURANCE',
  'AWP','DAYSSUPPLY','CARRIERID','ACCOUNTID','GROUPID','LINEOFBUSINESS','REVERSEDTRANID',
  'PRESCRIBERID','PHARMACYNPI','PRESCRIPTIONORIGINCODE','FILLNUMBER','PRESCRIPTIONWRITTENDATE',
  'DAWPENALTY','PERSONCODE','GROUPCODE','SUBSCRIBERSSN','SOURCEFILENAME','FILE_RECEIVED_DATE','IMPORT_DATE'
];
export const PMO_RAW_FIELDS = [
  'MEMBER_ID','CLAIM_ID','THERAPEUTIC_EQUIVALENCE_INDICATOR','GROUP_ID',
  'GCN_SEQUENCE_NUMBER','COMPOUND_FLAG','OVER_THE_COUNTER_FLAG','DRUG_TYPE',
  'PRESCRIBER_ID','PRESCRIBER_NAME','MAINTENANCE_DRUG_FLAG','PROVIDER_DEA_NUMBER',
  'PROVIDER_NPI','PHARMACY_NABP_NUMBER','PHARMACYNAME','WRITTEN_DATE','FILLED_DATE',
  'PAID_DATE','NDC_CODE','NDC_DESCRIPTION','SPECIALTY_INDICATOR','DRUG_NAME',
  'DRUG_DOSAGE','DRUG_STRENGTH','UNIT_QUANTITY','DAY_OF_SUPPLY','FORMULARY_FLAG',
  'MAIL_ORDER_FLAG','UNIT_PRICE','PACKAGE_PRICE','ROUTE_OF_ADMINISTRATION',
  'REFILL_QUANTITY','DISPENSED_AS_WRITTEN_CODE','ALLOWED_AMOUNT','BILLED_AMOUNT',
  'COINSURANCE_AMOUNT','COPAY_AMOUNT','DEDUCTIBLE_AMOUNT','PAID_AMOUNT',
  'PHARMACY_NPI','PHARMACY_STATE','PHARMACY_ZIP_CODE','DRUG_CATEGORY_CODE',
  'AWP','INGREDIENT_COST','FIRST_NAME','LAST_NAME','DOB','GENDER','MEMBER_SSN',
  'SOURCEFILENAME','FILE_RECEIVED_DATE','IMPORT_DATE'
];

export const PX_MAX_FIELDS = new Set(['SOURCEFILENAME','FILE_RECEIVED_DATE','IMPORT_DATE']);

export const PX_STAGE_DDL = [
  'CH_PHARMACY_CLAIM_ID VARCHAR(16777216)','RECORD_ID VARCHAR(16777216)','MEMBER_ID VARCHAR(16777216)',
  'CLAIM_ID VARCHAR(16777216)','THERAPEUTIC_EQUIVALENCE_INDICATOR VARCHAR(16777216)',
  'THERAPEUTIC_EQUIVALENCE_INDICATOR_DESCRIPTION VARCHAR(16777216)','GROUP_ID VARCHAR(16777216)',
  'GCN_SEQUENCE_NUMBER VARCHAR(16777216)','CH_MEMBER_ID VARCHAR(16777216)','CH_EMPLOYER_ID VARCHAR(16777216)',
  'COMPOUND_FLAG VARCHAR(16777216)','OVER_THE_COUNTER_FLAG VARCHAR(16777216)','DRUG_TYPE VARCHAR(16777216)',
  'PRESCRIBER_ID VARCHAR(16777216)','PRESCRIBER_FIRST_NAME VARCHAR(16777216)','MAINTENANCE_DRUG_FLAG VARCHAR(16777216)',
  'CATEGORY_NUMBER VARCHAR(16777216)','PRESCRIBER_MIDDLE_NAME VARCHAR(16777216)','PRESCRIBER_LAST_NAME VARCHAR(16777216)',
  'CATEGORY_DESCRIPTION VARCHAR(16777216)','PROVIDER_DEA_NUMBER VARCHAR(16777216)','PROVIDER_NPI VARCHAR(16777216)',
  'PROVIDER_NABP_NUMBER VARCHAR(16777216)','PHARMACY_NAME VARCHAR(16777216)','WRITTEN_DATE DATE',
  'FILLED_DATE DATE','PAID_DATE DATE','DIAGNOSIS_CODE VARCHAR(16777216)','DIAGNOSIS_DESCRIPTION VARCHAR(16777216)',
  'NDC_CODE VARCHAR(16777216)','NDC_DESCRIPTION VARCHAR(16777216)','SPECIALTY_DRUG_FLAG VARCHAR(16777216)',
  'PRESCRIPTION_CLASS_CODE VARCHAR(16777216)','PRESCRIPTION_CLASS_DESCRIPTION VARCHAR(16777216)',
  'BRAND_CODE VARCHAR(16777216)','DRUG_NAME VARCHAR(16777216)','DRUG_DOSAGE VARCHAR(16777216)',
  'DRUG_STRENGTH VARCHAR(16777216)','UNIT_QUANTITY FLOAT','DAYS_OF_SUPPLY VARCHAR(16777216)',
  'PRESCRIPTION_LABEL_NAME VARCHAR(16777216)','FORMULARY_FLAG VARCHAR(16777216)','GENERIC_FLAG VARCHAR(16777216)',
  'MAIL_ORDER_FLAG VARCHAR(16777216)','UNIT_PRICE FLOAT','PACKAGE_PRICE FLOAT',
  'DUPLICATE_THERAPY_CLASS_ID VARCHAR(16777216)','DUPLICATE_THERAPY_DESCRIPTION VARCHAR(16777216)',
  'DUPLICATE_THERAPY_ALLOWANCE_NUMBER VARCHAR(16777216)','HIC3_CODE VARCHAR(16777216)',
  'HIC3_DESCRIPTION VARCHAR(16777216)','ROUTE_OF_ADMINISTRATION VARCHAR(16777216)','REFILL_QUANTITY FLOAT',
  'REFILLS_ALLOWED_NUMBER FLOAT','DISPENSED_AS_WRITTEN_CODE VARCHAR(16777216)',
  'DISPENSED_AS_WRITTEN_DESCRIPTION VARCHAR(16777216)','ALLOWED_AMOUNT FLOAT','BILLED_AMOUNT FLOAT',
  'COINSURANCE_AMOUNT FLOAT','COPAY_AMOUNT FLOAT','DEDUCTIBLE_AMOUNT FLOAT','DISPENSING_FEE_AMOUNT FLOAT',
  'INGREDIENT_COST_AMOUNT FLOAT','STATE_TAX_AMOUNT FLOAT','USUAL_CUSTOMARY_FEE_AMOUNT FLOAT',
  'PAID_AMOUNT FLOAT','PHARMACY_NPI VARCHAR(16777216)','PHARMACY_STATE VARCHAR(16777216)',
  'PHARMACY_ZIP_CODE VARCHAR(16777216)','PRESCRIPTION_GENERIC_BRAND_INDICATOR VARCHAR(16777216)',
  'ADJUDICATION_DESCRIPTION VARCHAR(16777216)','GPI10_CODE VARCHAR(16777216)','CARDHOLDER_ID VARCHAR(16777216)',
  'CLIENT_ACCOUNT_ID VARCHAR(16777216)','DAYS_SUPPLY_INTENDED_TO_BE_DISPENSED FLOAT',
  'DISPENSING_STATUS VARCHAR(16777216)','DRUG_CATEGORY_CODE VARCHAR(16777216)','OTHER_PAYER_AMOUNT FLOAT',
  'PROFESSIONAL_SERVICE_CODE_1 VARCHAR(16777216)','PROFESSIONAL_SERVICE_CODE_2 VARCHAR(16777216)',
  'PROFESSIONAL_SERVICE_CODE_3 VARCHAR(16777216)','QUANTITY_INTENDED_TO_BE_DISPENSED FLOAT',
  'REASON_FOR_SERVICE_CODE_1 VARCHAR(16777216)','REASON_FOR_SERVICE_CODE_2 VARCHAR(16777216)',
  'REASON_FOR_SERVICE_CODE_3 VARCHAR(16777216)','RESULT_OF_SERVICE_CODE_1 VARCHAR(16777216)',
  'RESULT_OF_SERVICE_CODE_2 VARCHAR(16777216)','RESULT_OF_SERVICE_CODE_3 VARCHAR(16777216)',
  'SERVICE_PROVIDER_ID VARCHAR(16777216)','UNIT_OF_MEASURE VARCHAR(16777216)','MERGE_DT DATE',
  'MERGED_FROM_CH_MEMBER_ID VARCHAR(16777216)','MERGED_FROM_MEMBER_ID VARCHAR(16777216)',
  'SOURCEFILENAME VARCHAR(16777216)','RECEIVED_DATE DATE','IMPORT_DATE DATE','SCRUBBED_DATE DATE',
  'AWP FLOAT','UDF1 VARCHAR(16777216)','UDF2 VARCHAR(16777216)','UDF3 VARCHAR(16777216)',
  'UDF4 VARCHAR(16777216)','UDF5 VARCHAR(16777216)','UDF6 VARCHAR(16777216)','UDF7 VARCHAR(16777216)',
  'UDF8 VARCHAR(16777216)','UDF9 VARCHAR(16777216)','UDF10 VARCHAR(16777216)'
];

export const PX_DEFAULTS = [
  {target:'CH_PHARMACY_CLAIM_ID',type:'null',value:''},
  {target:'RECORD_ID',type:'null',value:''},
  {target:'MEMBER_ID',type:'expression',value:"MEMBERID||PERSONCODE"},
  {target:'CLAIM_ID',type:'direct',value:'TRANSACTIONID'},
  {target:'THERAPEUTIC_EQUIVALENCE_INDICATOR',type:'null',value:''},
  {target:'THERAPEUTIC_EQUIVALENCE_INDICATOR_DESCRIPTION',type:'null',value:''},
  {target:'GROUP_ID',type:'direct',value:'GROUPID'},
  {target:'GCN_SEQUENCE_NUMBER',type:'direct',value:'GCN'},
  {target:'CH_MEMBER_ID',type:'null',value:''},
  {target:'CH_EMPLOYER_ID',type:'hardcoded',value:'810'},
  {target:'COMPOUND_FLAG',type:'expression',value:"CASE WHEN COMPOUNDCODE IN ('2') THEN 'Y' WHEN COMPOUNDCODE = '1' THEN 'N' ELSE 'U' END"},
  {target:'OVER_THE_COUNTER_FLAG',type:'expression',value:"CASE WHEN RXOTCINDICATION = 'YES' THEN 'Y' WHEN RXOTCINDICATION = 'NO' THEN 'N' ELSE 'U' END"},
  {target:'DRUG_TYPE',type:'expression',value:"CASE WHEN DRUGTYPE IN ('GEN') THEN 'GENERIC' WHEN DRUGTYPE IN ('MSB','SSB','Branded Generic') THEN 'BRANDED' ELSE 'UNKNOWN' END"},
  {target:'PRESCRIBER_ID',type:'direct',value:'PRESCRIBERID'},
  {target:'PRESCRIBER_FIRST_NAME',type:'direct',value:'PRESCRIBINGPHYSICIAN'},
  {target:'MAINTENANCE_DRUG_FLAG',type:'null',value:''},
  {target:'CATEGORY_NUMBER',type:'null',value:''},
  {target:'PRESCRIBER_MIDDLE_NAME',type:'null',value:''},
  {target:'PRESCRIBER_LAST_NAME',type:'null',value:''},
  {target:'CATEGORY_DESCRIPTION',type:'null',value:''},
  {target:'PROVIDER_DEA_NUMBER',type:'direct',value:'DOCTORDEA'},
  {target:'PROVIDER_NPI',type:'direct',value:'PRESCRIBERID'},
  {target:'PROVIDER_NABP_NUMBER',type:'null',value:''},
  {target:'PHARMACY_NAME',type:'direct',value:'PHARMACYNAME'},
  {target:'WRITTEN_DATE',type:'expression',value:"TO_DATE(PRESCRIPTIONWRITTENDATE::VARCHAR,'MM/DD/YYYY')"},
  {target:'FILLED_DATE',type:'expression',value:"TO_DATE(SERVICEDATE::VARCHAR,'MM/DD/YYYY')"},
  {target:'PAID_DATE',type:'expression',value:"TO_DATE(TRANSACTIONDATE::VARCHAR,'MM/DD/YYYY')"},
  {target:'DIAGNOSIS_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_DESCRIPTION',type:'null',value:''},
  {target:'NDC_CODE',type:'expression',value:"LPAD(NDC,11,'0')"},
  {target:'NDC_DESCRIPTION',type:'direct',value:'LABELNAME'},
  {target:'SPECIALTY_DRUG_FLAG',type:'expression',value:"CASE WHEN SPECIALTY = 'YES' THEN 'Y' WHEN SPECIALTY = 'NO' THEN 'N' ELSE 'U' END"},
  {target:'PRESCRIPTION_CLASS_CODE',type:'null',value:''},
  {target:'PRESCRIPTION_CLASS_DESCRIPTION',type:'null',value:''},
  {target:'BRAND_CODE',type:'null',value:''},
  {target:'DRUG_NAME',type:'direct',value:'DRUGNAME'},
  {target:'DRUG_DOSAGE',type:'direct',value:'DOSAGEFORM'},
  {target:'DRUG_STRENGTH',type:'direct',value:'DRUGSTRENGTH'},
  {target:'UNIT_QUANTITY',type:'direct',value:'QUANTITYDISPENSED'},
  {target:'DAYS_OF_SUPPLY',type:'expression',value:'CAST(DAYSSUPPLY AS INT)'},
  {target:'PRESCRIPTION_LABEL_NAME',type:'null',value:''},
  {target:'FORMULARY_FLAG',type:'expression',value:"CASE WHEN FORMULARYINDICATOR = 'YES' THEN 'Y' WHEN FORMULARYINDICATOR = 'NO' THEN 'N' ELSE 'N' END"},
  {target:'GENERIC_FLAG',type:'expression',value:"CASE WHEN DRUGTYPE = 'GEN' THEN 'Y' ELSE 'N' END"},
  {target:'MAIL_ORDER_FLAG',type:'null',value:''},
  {target:'UNIT_PRICE',type:'null',value:''},
  {target:'PACKAGE_PRICE',type:'null',value:''},
  {target:'DUPLICATE_THERAPY_CLASS_ID',type:'null',value:''},
  {target:'DUPLICATE_THERAPY_DESCRIPTION',type:'null',value:''},
  {target:'DUPLICATE_THERAPY_ALLOWANCE_NUMBER',type:'null',value:''},
  {target:'HIC3_CODE',type:'null',value:''},
  {target:'HIC3_DESCRIPTION',type:'null',value:''},
  {target:'ROUTE_OF_ADMINISTRATION',type:'null',value:''},
  {target:'REFILL_QUANTITY',type:'direct',value:'FILLNUMBER'},
  {target:'REFILLS_ALLOWED_NUMBER',type:'null',value:''},
  {target:'DISPENSED_AS_WRITTEN_CODE',type:'direct',value:'DAWCODE'},
  {target:'DISPENSED_AS_WRITTEN_DESCRIPTION',type:'expression',value:"CASE WHEN DAWCODE='0' THEN 'No Product Selection Indicated' WHEN DAWCODE='1' THEN 'Substitution Not Allowed by Prescriber' WHEN DAWCODE='2' THEN 'Substitution Allowed - Patient Requested Product Dispensed' WHEN DAWCODE='3' THEN 'Substitution Allowed - Pharmacist Selected Product Dispensed' WHEN DAWCODE='4' THEN 'Substitution Allowed - Generic Drug Not in Stock' WHEN DAWCODE='5' THEN 'Substitution Allowed - Brand Drug Dispensed as Generic' WHEN DAWCODE='6' THEN 'Override' WHEN DAWCODE='7' THEN 'Substitution Not Allowed - Brand Drug Mandated by Law' WHEN DAWCODE='8' THEN 'Substitution Allowed - Generic Drug Not Available in Marketplace' WHEN DAWCODE='9' THEN 'Substitution Allowed By Prescriber but Plan Requests Brand' ELSE DAWCODE END"},
  {target:'ALLOWED_AMOUNT',type:'direct',value:'GROSSAMTDUE'},
  {target:'BILLED_AMOUNT',type:'direct',value:'GROSSAMTDUE'},
  {target:'COINSURANCE_AMOUNT',type:'direct',value:'COINSURANCE'},
  {target:'COPAY_AMOUNT',type:'direct',value:'COPAY'},
  {target:'DEDUCTIBLE_AMOUNT',type:'direct',value:'DEDUCTIBLEAMT'},
  {target:'DISPENSING_FEE_AMOUNT',type:'direct',value:'DISPFEEPAID'},
  {target:'INGREDIENT_COST_AMOUNT',type:'direct',value:'INGREDIENTCOST'},
  {target:'STATE_TAX_AMOUNT',type:'direct',value:'SALESTAX'},
  {target:'USUAL_CUSTOMARY_FEE_AMOUNT',type:'direct',value:'USUALANDCUST'},
  {target:'PAID_AMOUNT',type:'expression',value:'PLANPAID+PATIENTPAID'},
  {target:'PHARMACY_NPI',type:'direct',value:'PHARMACYNPI'},
  {target:'PHARMACY_STATE',type:'direct',value:'PHARMACYSTATE'},
  {target:'PHARMACY_ZIP_CODE',type:'direct',value:'PHARMACYZIPCODE'},
  {target:'PRESCRIPTION_GENERIC_BRAND_INDICATOR',type:'null',value:''},
  {target:'ADJUDICATION_DESCRIPTION',type:'null',value:''},
  {target:'GPI10_CODE',type:'direct',value:'GPICODE'},
  {target:'CARDHOLDER_ID',type:'null',value:''},
  {target:'CLIENT_ACCOUNT_ID',type:'direct',value:'ACCOUNTID'},
  {target:'DAYS_SUPPLY_INTENDED_TO_BE_DISPENSED',type:'null',value:''},
  {target:'DISPENSING_STATUS',type:'null',value:''},
  {target:'DRUG_CATEGORY_CODE',type:'expression',value:"CASE WHEN DRUGTYPE = 'GEN' THEN 'GENERIC' WHEN DRUGTYPE = 'MSB' THEN 'MULTI SOURCE BRAND' WHEN DRUGTYPE = 'SSB' THEN 'SINGLE SOURCE BRAND' WHEN DRUGTYPE = 'BRANDED GENERIC' THEN 'BRANDED GENERIC' ELSE 'UNKNOWN' END"},
  {target:'OTHER_PAYER_AMOUNT',type:'null',value:''},
  {target:'PROFESSIONAL_SERVICE_CODE_1',type:'null',value:''},
  {target:'PROFESSIONAL_SERVICE_CODE_2',type:'null',value:''},
  {target:'PROFESSIONAL_SERVICE_CODE_3',type:'null',value:''},
  {target:'QUANTITY_INTENDED_TO_BE_DISPENSED',type:'null',value:''},
  {target:'REASON_FOR_SERVICE_CODE_1',type:'null',value:''},
  {target:'REASON_FOR_SERVICE_CODE_2',type:'null',value:''},
  {target:'REASON_FOR_SERVICE_CODE_3',type:'null',value:''},
  {target:'RESULT_OF_SERVICE_CODE_1',type:'null',value:''},
  {target:'RESULT_OF_SERVICE_CODE_2',type:'null',value:''},
  {target:'RESULT_OF_SERVICE_CODE_3',type:'null',value:''},
  {target:'SERVICE_PROVIDER_ID',type:'null',value:''},
  {target:'UNIT_OF_MEASURE',type:'direct',value:'DOSAGEFORM'},
  {target:'MERGE_DT',type:'null',value:''},
  {target:'MERGED_FROM_CH_MEMBER_ID',type:'null',value:''},
  {target:'MERGED_FROM_MEMBER_ID',type:'null',value:''},
  {target:'SOURCEFILENAME',type:'direct',value:'SOURCEFILENAME'},
  {target:'RECEIVED_DATE',type:'direct',value:'FILE_RECEIVED_DATE'},
  {target:'IMPORT_DATE',type:'direct',value:'IMPORT_DATE'},
  {target:'SCRUBBED_DATE',type:'expression',value:'CURRENT_DATE()'},
  {target:'AWP',type:'direct',value:'AWP'},
  {target:'UDF1',type:'expression',value:"IFNULL(MEMBERFIRSTNAME,'X')||'_'||IFNULL(MEMBERLASTNAME,'X')||'_'||COALESCE(TO_DATE(BIRTHDATE::VARCHAR,'MM/DD/YYYY'),'99991231')||'_'||IFNULL(MEMBERGENDER,'U')"},
  {target:'UDF2',type:'direct',value:'TRANSTATUS'},
  {target:'UDF3',type:'direct',value:'SUBSCRIBERSSN'},
  {target:'UDF4',type:'direct',value:'PLANPAID'},
  {target:'UDF5',type:'direct',value:'PATIENTPAID'},
  {target:'UDF6',type:'direct',value:'GNN'},
  {target:'UDF7',type:'direct',value:'OOP'},
  {target:'UDF8',type:'direct',value:'SPECIALTY'},
  {target:'UDF9',type:'direct',value:'PCN'},
  {target:'UDF10',type:'null',value:''},
];



export const PMO_DEFAULTS = [
  {target:'CH_PHARMACY_CLAIM_ID',type:'null',value:''},
  {target:'RECORD_ID',type:'null',value:''},
  {target:'MEMBER_ID',type:'expression',value:"COALESCE(UPPER(FIRST_NAME),'X')||'_'||COALESCE(UPPER(LAST_NAME),'X')||'_'||COALESCE(TO_DATE(DOB,'MMDDYYYY'),'9999-12-31')||'_'||CASE WHEN UPPER(GENDER) = 'FEMALE' THEN 'F' WHEN UPPER(GENDER) = 'MALE' THEN 'M' ELSE 'U' END"},
  {target:'CLAIM_ID',type:'expression',value:"MEMBER_ID||'_'||CLAIM_ID"},
  {target:'THERAPEUTIC_EQUIVALENCE_INDICATOR',type:'null',value:''},
  {target:'THERAPEUTIC_EQUIVALENCE_INDICATOR_DESCRIPTION',type:'null',value:''},
  {target:'GROUP_ID',type:'null',value:''},
  {target:'GCN_SEQUENCE_NUMBER',type:'direct',value:'GCN_SEQUENCE_NUMBER'},
  {target:'CH_MEMBER_ID',type:'null',value:''},
  {target:'CH_EMPLOYER_ID',type:'null',value:''},
  {target:'COMPOUND_FLAG',type:'direct',value:'COMPOUND_FLAG'},
  {target:'OVER_THE_COUNTER_FLAG',type:'direct',value:'OVER_THE_COUNTER_FLAG'},
  {target:'DRUG_TYPE',type:'expression',value:"CASE WHEN UPPER(DRUG_TYPE) = 'G' THEN 'GENERIC' WHEN UPPER(DRUG_TYPE) = 'B' THEN 'BRAND' ELSE DRUG_TYPE END"},
  {target:'PRESCRIBER_ID',type:'direct',value:'PRESCRIBER_ID'},
  {target:'PRESCRIBER_FIRST_NAME',type:'direct',value:'PRESCRIBER_NAME'},
  {target:'MAINTENANCE_DRUG_FLAG',type:'direct',value:'MAINTENANCE_DRUG_FLAG'},
  {target:'CATEGORY_NUMBER',type:'null',value:''},
  {target:'PRESCRIBER_MIDDLE_NAME',type:'null',value:''},
  {target:'PRESCRIBER_LAST_NAME',type:'null',value:''},
  {target:'CATEGORY_DESCRIPTION',type:'null',value:''},
  {target:'PROVIDER_DEA_NUMBER',type:'direct',value:'PROVIDER_DEA_NUMBER'},
  {target:'PROVIDER_NPI',type:'expression',value:"LPAD(PROVIDER_NPI,10,'0')"},
  {target:'PROVIDER_NABP_NUMBER',type:'direct',value:'PHARMACY_NABP_NUMBER'},
  {target:'PHARMACY_NAME',type:'expression',value:'UPPER(PHARMACYNAME)'},
  {target:'WRITTEN_DATE',type:'expression',value:"TO_DATE(WRITTEN_DATE,'MMDDYYYY')"},
  {target:'FILLED_DATE',type:'expression',value:"TO_DATE(FILLED_DATE,'MMDDYYYY')"},
  {target:'PAID_DATE',type:'expression',value:"TO_DATE(PAID_DATE,'MMDDYYYY')"},
  {target:'DIAGNOSIS_CODE',type:'null',value:''},
  {target:'DIAGNOSIS_DESCRIPTION',type:'null',value:''},
  {target:'NDC_CODE',type:'expression',value:"LPAD(NDC_CODE,11,'0')"},
  {target:'NDC_DESCRIPTION',type:'expression',value:'UPPER(NDC_DESCRIPTION)'},
  {target:'SPECIALTY_DRUG_FLAG',type:'expression',value:'UPPER(SPECIALTY_INDICATOR)'},
  {target:'PRESCRIPTION_CLASS_CODE',type:'null',value:''},
  {target:'PRESCRIPTION_CLASS_DESCRIPTION',type:'null',value:''},
  {target:'BRAND_CODE',type:'null',value:''},
  {target:'DRUG_NAME',type:'expression',value:'UPPER(DRUG_NAME)'},
  {target:'DRUG_DOSAGE',type:'direct',value:'DRUG_DOSAGE'},
  {target:'DRUG_STRENGTH',type:'direct',value:'DRUG_STRENGTH'},
  {target:'UNIT_QUANTITY',type:'direct',value:'UNIT_QUANTITY'},
  {target:'DAYS_OF_SUPPLY',type:'direct',value:'DAY_OF_SUPPLY'},
  {target:'PRESCRIPTION_LABEL_NAME',type:'null',value:''},
  {target:'FORMULARY_FLAG',type:'direct',value:'FORMULARY_FLAG'},
  {target:'GENERIC_FLAG',type:'expression',value:"CASE WHEN UPPER(DRUG_TYPE) = 'GENERIC' THEN 'Y' ELSE 'N' END"},
  {target:'MAIL_ORDER_FLAG',type:'direct',value:'MAIL_ORDER_FLAG'},
  {target:'UNIT_PRICE',type:'direct',value:'UNIT_PRICE'},
  {target:'PACKAGE_PRICE',type:'direct',value:'PACKAGE_PRICE'},
  {target:'DUPLICATE_THERAPY_CLASS_ID',type:'null',value:''},
  {target:'DUPLICATE_THERAPY_DESCRIPTION',type:'null',value:''},
  {target:'DUPLICATE_THERAPY_ALLOWANCE_NUMBER',type:'null',value:''},
  {target:'HIC3_CODE',type:'null',value:''},
  {target:'HIC3_DESCRIPTION',type:'null',value:''},
  {target:'ROUTE_OF_ADMINISTRATION',type:'direct',value:'ROUTE_OF_ADMINISTRATION'},
  {target:'REFILL_QUANTITY',type:'direct',value:'REFILL_QUANTITY'},
  {target:'REFILLS_ALLOWED_NUMBER',type:'null',value:''},
  {target:'DISPENSED_AS_WRITTEN_CODE',type:'direct',value:'DISPENSED_AS_WRITTEN_CODE'},
  {target:'DISPENSED_AS_WRITTEN_DESCRIPTION',type:'null',value:''},
  {target:'ALLOWED_AMOUNT',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(BILLED_AMOUNT,18,2))'},
  {target:'BILLED_AMOUNT',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(BILLED_AMOUNT,18,2))'},
  {target:'COINSURANCE_AMOUNT',type:'direct',value:'COINSURANCE_AMOUNT'},
  {target:'COPAY_AMOUNT',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(COPAY_AMOUNT,18,2))'},
  {target:'DEDUCTIBLE_AMOUNT',type:'direct',value:'DEDUCTIBLE_AMOUNT'},
  {target:'DISPENSING_FEE_AMOUNT',type:'hardcoded',value:'0.00'},
  {target:'INGREDIENT_COST_AMOUNT',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(INGREDIENT_COST,18,2))'},
  {target:'STATE_TAX_AMOUNT',type:'hardcoded',value:'0.00'},
  {target:'USUAL_CUSTOMARY_FEE_AMOUNT',type:'hardcoded',value:'0.00'},
  {target:'PAID_AMOUNT',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(COINSURANCE_AMOUNT,18,2))+TO_VARCHAR(TO_DECIMAL(COPAY_AMOUNT,18,2))+TO_VARCHAR(TO_DECIMAL(DEDUCTIBLE_AMOUNT,18,2))+TO_VARCHAR(TO_DECIMAL(PAID_AMOUNT,18,2))'},
  {target:'PHARMACY_NPI',type:'direct',value:'PHARMACY_NPI'},
  {target:'PHARMACY_STATE',type:'direct',value:'PHARMACY_STATE'},
  {target:'PHARMACY_ZIP_CODE',type:'direct',value:'PHARMACY_ZIP_CODE'},
  {target:'PRESCRIPTION_GENERIC_BRAND_INDICATOR',type:'expression',value:"CASE WHEN UPPER(DRUG_TYPE) = 'G' THEN 'GENERIC' WHEN UPPER(DRUG_TYPE) = 'B' THEN 'BRAND' ELSE DRUG_TYPE END"},
  {target:'ADJUDICATION_DESCRIPTION',type:'null',value:''},
  {target:'GPI10_CODE',type:'null',value:''},
  {target:'CARDHOLDER_ID',type:'null',value:''},
  {target:'CLIENT_ACCOUNT_ID',type:'null',value:''},
  {target:'DAYS_SUPPLY_INTENDED_TO_BE_DISPENSED',type:'null',value:''},
  {target:'DISPENSING_STATUS',type:'null',value:''},
  {target:'DRUG_CATEGORY_CODE',type:'direct',value:'DRUG_CATEGORY_CODE'},
  {target:'OTHER_PAYER_AMOUNT',type:'null',value:''},
  {target:'PROFESSIONAL_SERVICE_CODE_1',type:'null',value:''},
  {target:'PROFESSIONAL_SERVICE_CODE_2',type:'null',value:''},
  {target:'PROFESSIONAL_SERVICE_CODE_3',type:'null',value:''},
  {target:'QUANTITY_INTENDED_TO_BE_DISPENSED',type:'null',value:''},
  {target:'REASON_FOR_SERVICE_CODE_1',type:'null',value:''},
  {target:'REASON_FOR_SERVICE_CODE_2',type:'null',value:''},
  {target:'REASON_FOR_SERVICE_CODE_3',type:'null',value:''},
  {target:'RESULT_OF_SERVICE_CODE_1',type:'null',value:''},
  {target:'RESULT_OF_SERVICE_CODE_2',type:'null',value:''},
  {target:'RESULT_OF_SERVICE_CODE_3',type:'null',value:''},
  {target:'SERVICE_PROVIDER_ID',type:'null',value:''},
  {target:'UNIT_OF_MEASURE',type:'null',value:''},
  {target:'MERGE_DT',type:'null',value:''},
  {target:'MERGED_FROM_CH_MEMBER_ID',type:'null',value:''},
  {target:'MERGED_FROM_MEMBER_ID',type:'null',value:''},
  {target:'SOURCEFILENAME',type:'direct',value:'SOURCEFILENAME'},
  {target:'RECEIVED_DATE',type:'direct',value:'FILE_RECEIVED_DATE'},
  {target:'IMPORT_DATE',type:'direct',value:'IMPORT_DATE'},
  {target:'SCRUBBED_DATE',type:'expression',value:'CURRENT_DATE()'},
  {target:'AWP',type:'direct',value:'AWP'},
  {target:'UDF1',type:'null',value:''},
  {target:'UDF2',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(COINSURANCE_AMOUNT,18,2))+TO_VARCHAR(TO_DECIMAL(COPAY_AMOUNT,18,2))+TO_VARCHAR(TO_DECIMAL(DEDUCTIBLE_AMOUNT,18,2))'},
  {target:'UDF3',type:'expression',value:'TO_VARCHAR(TO_DECIMAL(PAID_AMOUNT,18,2))'},
  {target:'UDF4',type:'null',value:''},
  {target:'UDF5',type:'null',value:''},
  {target:'UDF6',type:'null',value:''},
  {target:'UDF7',type:'direct',value:'MEMBER_SSN'},
  {target:'UDF8',type:'null',value:''},
  {target:'UDF9',type:'null',value:''},
  {target:'UDF10',type:'hardcoded',value:'MEDONE'},
];